# Generated by Django 3.1.6 on 2021-08-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=30)),
                ('contactdetails', models.CharField(max_length=60)),
                ('yearofpassing', models.IntegerField()),
            ],
        ),
    ]
