# Generated by Django 3.1.6 on 2021-08-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=60)),
            ],
        ),
    ]
