# Generated by Django 3.1.6 on 2021-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('donername', models.CharField(max_length=200)),
                ('payment_id', models.CharField(max_length=100)),
            ],
        ),
    ]
