# Generated by Django 3.1.6 on 2021-08-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_mapper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departmentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('hodid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hod')),
                ('universityid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.university')),
            ],
        ),
    ]
