# Generated by Django 3.1.6 on 2021-08-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_faculty_mapper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_mapper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course')),
                ('departmentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('studentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('universityid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.university')),
            ],
        ),
    ]
