# Generated by Django 3.1.6 on 2021-08-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rollno_mapper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_mapper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departmentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('eventid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.event')),
            ],
        ),
    ]
